### ISSUE TITLE
no show for img

### ISSUE THREAD

**Issue by bobjiang** [erizhang/systemdynamics#2]
don't show CLD 

img for population exercises

systemdynamics/docs/exercises/loops_city_population.md

![wechatimg68](https://user-images.githubusercontent.com/1224604/30797642-50477c48-a209-11e7-9804-f9d58e20eeb0.jpeg)

**Comment by erizhang** [comment]
fixed by commit: 7628f51f5a7de5e85be7685402b5a78b709f3a20
